export const GET_ALL_DEPARTMENTS_SUCCESS = "GET_ALL_DEPARTMENTS_SUCCESS";
export const GET_ALL_POSITIONS_SUCCESS = "GET_ALL_POSITIONS_SUCCESS";
export const GET_ALL_EMPLOYEES_SUCCESS = "GET_ALL_EMPLOYEES_SUCCESS";
export const GET_ALL_FORMER_EMPLOYEES_SUCCESS = "GET_ALL_FORMER_EMPLOYEES_SUCCESS";